version: '3'
services:
  web:
    image: nginx:alpine
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./server:/var/www/html
  app:
    build: ./server
    ports:
      - 8000:8000
    volumes:
      - ./server/api/v1/:/var/www/html
